// The tier checks. Passing one pays the bulk of that rung's coins and unlocks its capability,
// so these are the actual gate on the prestige ladder and they are meant to be hard.
//
// Each tier holds a pool larger than the check draws from it, and options are shuffled at
// runtime, so a retake is a different paper rather than a memory test on button positions.
// `answer` indexes into `options` as written here; the quiz remaps it after shuffling.
//
// Chart questions carry a spec rendered by chart.js. Those specs are seeded, so the chart in
// the question is always the same chart, and every answer below was checked against the data
// the generator actually produces rather than against what it seemed like it ought to produce.

export const CHECKS = {
  1: [
    { q: "What actually gives a coin its value?",
      options: ["An agreement that others will honour it as a claim on goods and labour",
                "The material it is made from",
                "A government guarantee that its purchasing power will not fall",
                "The total quantity of it in circulation"],
      answer: 0,
      why: "Nothing physical about money carries value. The agreement does — which is why it can be honoured well or badly." },
    { q: "A market price mainly conveys:",
      options: ["The terms the marginal buyer and marginal seller agree on, aggregating what each of them separately knows",
                "The average opinion of everyone who owns the asset",
                "The cost of producing the thing",
                "What the largest holder believes it is worth"],
      answer: 0,
      why: "It is the summary of a disagreement at the margin, which is how a price ends up carrying information no individual in the market possesses." },
    { q: "A government caps a price below where the market would clear. What has certainly been destroyed?",
      options: ["The information the price was carrying",
                "The underlying scarcity",
                "The demand for the good",
                "The cost of producing it"],
      answer: 0,
      why: "Hayek's point. Suppressing a price makes nothing more plentiful; it only destroys the message that would have redirected resources." },
    { q: "\"It made money, so it was a good decision.\" What is wrong with this?",
      options: ["A decision can only be judged against the alternatives available at the time, and a good outcome can follow a bad decision",
                "Nothing — profit is the only test that matters",
                "It ignores tax",
                "Returns should always be measured after inflation"],
      answer: 0,
      why: "Outcome and decision quality are different things. This is why every table in the game shows a counterfactual beside your bank." },
    { q: "The real cost of spending an hour studying charts is:",
      options: ["The most valuable thing you would otherwise have done with that hour",
                "Zero, because your time was already paid for",
                "The subscription cost of the charting software",
                "Whatever you earn per hour at your job"],
      answer: 0,
      why: "Opportunity cost is the next best option you gave up, not the sticker price and not nothing." },
    { q: "Which is NOT one of the two jobs money does?",
      options: ["Guaranteeing that what you saved will still buy the same basket later",
                "Moving value across space, so you can sell here and buy there",
                "Moving value across time, so you can work now and consume later",
                "Acting as a claim on goods other people have not yet produced"],
      answer: 0,
      why: "Money moves value across space and time. It emphatically does not guarantee the value survives the trip — that is what tier two is about." },
  ],

  2: [
    { q: "At 9% a year, roughly how long does money take to double?",
      options: ["About 8 years", "About 5 years", "About 12 years", "About 20 years"],
      answer: 0,
      why: "The rule of 72: 72 ÷ 9 = 8. Accurate enough to do in your head, which is the whole value of it." },
    { q: "Your money grows 6% while prices rise 4%. How much richer are you?",
      options: ["About 2%", "About 6%", "About 10%", "About 1.5%"],
      answer: 0,
      why: "Real ≈ nominal − inflation. The 6% is the number in the brochure; the 2% is the number that buys anything." },
    { q: "An interest rate bundles together:",
      options: ["Pure preference for having money now, expected inflation, and the risk of not being repaid",
                "Only the lender's cost of funds",
                "Only expected inflation",
                "The central bank's target and nothing else"],
      answer: 0,
      why: "When a rate moves, at least one of those three moved. Most monetary-policy arguments are really arguments about which one." },
    { q: "A 2% annual fee, paid on a pot compounding for 30 years, costs you roughly:",
      options: ["About 45% of the final pot", "About 2% of the final pot",
                "About 20% of the final pot", "About 60% of the final pot"],
      answer: 0,
      why: "Fees compound against you exactly as returns compound for you. This is the entire argument of the Sector Reels machine." },
    { q: "Inflation transfers value:",
      options: ["Away from holders of cash and fixed payments, toward holders of debt and assets",
                "Away from the rich, toward the poor",
                "Away from borrowers, toward lenders",
                "Evenly away from everybody, harming nobody in particular"],
      answer: 0,
      why: "A fixed nominal obligation gets cheaper to repay in real terms. Which is why the green zero on the wheel is labelled inflation." },
    { q: "10% a year for 30 years multiplies your money by roughly:",
      options: ["17×", "4×", "30×", "7×"],
      answer: 0,
      why: "Three doublings would be 8×; the rule of 72 gives a double every ~7.2 years, so 30 years is more than four doublings. Compounding is almost impossible to feel as a quantity." },
  ],

  3: [
    { q: "On the chart shown, which range is the candle's body?",
      options: ["100 to 108", "96 to 112", "100 to 112", "96 to 108"],
      answer: 0,
      why: "The body spans open to close. The wicks reach out to the high and the low — those are 112 and 96.",
      chart: { kind: "candle", o: 100, h: 112, l: 96, c: 108 } },
    { q: "A bar closes with a small body and a long upper wick. What does that record?",
      options: ["Buyers pushed the price up and could not hold it there",
                "A guaranteed reversal is coming",
                "Trading volume was unusually low",
                "The price gapped at the open"],
      answer: 0,
      why: "It is evidence about a level that was tried and rejected. Evidence about a level, never a signal about tomorrow.",
      chart: { kind: "shapes" } },
    { q: "Within a single candle, what information is irrecoverably lost?",
      options: ["The order in which the high, the low and the close happened",
                "The closing price",
                "The total range of the bar",
                "Whether the bar closed up or down"],
      answer: 0,
      why: "A crash-then-recover day and a rally-selloff-rally day can draw an identical candle. Four numbers kept, the whole sequence thrown away." },
    { q: "The same year of data is drawn as daily bars and as weekly bars. Which is true?",
      options: ["Both are accurate, and either can support a story the other contradicts",
                "The daily chart is the real one; weekly is a simplification",
                "The weekly chart is more reliable because it filters noise",
                "They will show the same highs and lows"],
      answer: 0,
      why: "Aggregation is a choice somebody made, not a property of the market. Always ask what timeframe this is and who picked it.",
      chart: { kind: "timeframe", seed: 31 } },
    { q: "By the convention used here and nearly everywhere, a light-coloured candle means:",
      options: ["The close was above the open", "The close was above the previous close",
                "Volume was above average", "The high was a new high for the series"],
      answer: 0,
      why: "Up and down candles are coloured by close versus open within that same bar — not versus the bar before it." },
    { q: "Someone shows you a dramatic chart. What is the first honest question?",
      options: ["What timeframe is this, and who chose the window?",
                "What was the highest price reached?",
                "Which indicator is overlaid on it?",
                "What was the total volume?"],
      answer: 0,
      why: "A chart cropped to the right window can argue almost anything. The timeframe and the crop are the argument." },
    { q: "\"Four numbers per bar\" refers to:",
      options: ["Open, high, low, close", "Bid, ask, last, volume",
                "High, low, volume, average", "Open, close, volume, range"],
      answer: 0,
      why: "OHLC. Every claim anyone has ever made about a chart is assembled from those four numbers and nothing else." },
  ],

  4: [
    { q: "A market makes a new high on clearly falling volume. The honest reading is:",
      options: ["Fewer and fewer participants are willing to pay up, so the move is unconfirmed",
                "A reversal is now certain",
                "The new high is invalid and should be ignored",
                "Volume has no bearing on a price move"],
      answer: 0,
      why: "Volume is a confidence measure on the move, not a signal in its own right. That framing survives contact with evidence; most of the rest does not.",
      chart: { kind: "candles", seed: 12, bars: 44, drift: 0.0035, vol: 0.016, volume: true } },
    { q: "A gap on a chart is:",
      options: ["A price range in which no trade ever happened",
                "A data error that should be cleaned",
                "A period when the price moved unusually fast",
                "A range where volume was very light"],
      answer: 0,
      why: "The price did not travel through it. No trades, no volume, and so no level anybody actually defended.",
      chart: { kind: "candles", seed: 5, bars: 40, drift: -0.001, vol: 0.014, gapAt: 22, gapBy: -0.09 } },
    { q: "Why does a stop-loss fail to protect you through a gap?",
      options: ["The market can reopen beyond your level, so there was never a trade at it to fill you",
                "Stops are not honoured during volatile sessions",
                "Gaps always reverse, so the stop fires needlessly",
                "Brokers suspend stops around news"],
      answer: 0,
      why: "This breaks the most common assumption in retail risk management. Your loss is set by where it reopens, not where you asked to exit." },
    { q: "On a logarithmic price axis, equal vertical distance represents:",
      options: ["Equal percentage change", "Equal dollar change",
                "Equal volume", "Equal elapsed time"],
      answer: 0,
      why: "Which is why a double is the same height wherever it starts. Linear axes make equal percentage moves look wildly unequal." },
    { q: "A move from 10 to 20 and a move from 100 to 200, drawn on a log axis:",
      options: ["Appear as the same height, because both are a double",
                "Appear ten times different, as they should",
                "Cannot be drawn on the same axis",
                "Appear the same only if volume was equal"],
      answer: 0,
      why: "For anything spanning more than a couple of doublings, linear is the misleading choice — most \"unprecedented parabola\" charts are a linear-axis artefact.",
      chart: { kind: "logdemo", seed: 9 } },
    { q: "Why is a candle in a very illiquid market close to meaningless?",
      options: ["A handful of small trades can print any shape, and you could not have transacted size at that price",
                "Illiquid markets are not reported accurately",
                "The exchange calculates the close differently",
                "Wicks cannot form without high volume"],
      answer: 0,
      why: "A price only means something if you could actually have traded at it. The candle looks just as authoritative either way." },
    { q: "In a healthy uptrend, the classical expectation for volume is that it:",
      options: ["Expands as price rises and contracts on pullbacks",
                "Stays constant throughout",
                "Contracts as price rises, showing efficient buying",
                "Is unrelated to the direction of the trend"],
      answer: 0,
      why: "One of the oldest ideas in the field, and among the few that is about confirmation rather than prediction." },
  ],

  5: [
    { q: "What separates \"this is an uptrend\" from \"this will continue\"?",
      options: ["The first is a measurement of the past; the second is a forecast and a much weaker claim",
                "Nothing — an uptrend is defined by its continuation",
                "The second is true whenever volume confirms it",
                "The first requires a moving average, the second does not"],
      answer: 0,
      why: "Momentum is a real, thin, decaying effect. Keeping those two sentences apart makes most chart-reading nonsense visible on contact.",
      chart: { kind: "candles", seed: 77, bars: 60, drift: 0.004, vol: 0.018, ma: [20] } },
    { q: "You are down 50% from your high. What gain gets you back to level?",
      options: ["+100%", "+50%", "+75%", "+150%"],
      answer: 0,
      why: "Losses and gains are not symmetric. An 80% fall needs 400%, and you have to survive the entire wait." },
    { q: "Two assets finish at exactly the same price after the same period, but one took a far wilder path. Which matters more for whether you actually captured that return?",
      options: ["The wilder path, because its deeper drawdown is what makes a position impossible to hold",
                "Neither — the finish is identical, so the outcome is identical",
                "The wilder path, because higher volatility means higher expected return",
                "The calmer path, because low volatility assets are riskier than they look"],
      answer: 0,
      why: "Average return is the brochure. Drawdown decides whether you were still there at the end.",
      chart: { kind: "drawdown", seed: 44 } },
    { q: "Shown two charts generated from pure coin flips, most people confidently identify trends, support levels and textbook formations. Why?",
      options: ["Humans are relentless pattern-matchers, and random walks genuinely contain those shapes by construction",
                "The charts were not really random",
                "Patterns in random data still predict future random data",
                "Support and resistance are properties of any number series"],
      answer: 0,
      why: "A pattern you can only see after the fact is not a pattern, it is a memory.",
      chart: { kind: "randomwalk", seed: 101 } },
    { q: "The test that distinguishes a real pattern from a story is:",
      options: ["Could the rule have been written down in advance, and does it still work on data you have not seen?",
                "Does it appear in the standard textbooks?",
                "Has it worked on this chart for several years?",
                "Do experienced traders agree it is there?"],
      answer: 0,
      why: "Specified in advance, tested out of sample. Almost nothing survives it." },
    { q: "What is price history genuinely good for?",
      options: ["Measuring volatility, correlation, drawdown and liquidity — the inputs to sizing a position",
                "Forecasting the direction of the next move",
                "Identifying which patterns are about to complete",
                "Nothing at all; charts are pure noise"],
      answer: 0,
      why: "Charts are for sizing the bet, not picking the side. Kelly needs a variance, and a variance comes off a chart." },
    { q: "An 80% drawdown requires what gain to recover?",
      options: ["+400%", "+80%", "+180%", "+800%"],
      answer: 0,
      why: "You keep 20p in the pound, so you need to quintuple it. The arithmetic of ruin is brutally asymmetric." },
  ],

  6: [
    { q: "Graham's central distinction is between:",
      options: ["The price you pay and the value you get",
                "Growth stocks and income stocks",
                "Long-term and short-term holding periods",
                "Technical and fundamental analysis"],
      answer: 0,
      why: "Two different numbers, related by nothing more reliable than eventual gravity." },
    { q: "Why insist on a margin of safety rather than simply buying at your estimate of value?",
      options: ["Because the estimate is a range, so buying at it puts roughly half your errors underwater immediately",
                "Because it guarantees a profit",
                "Because it lets you use leverage safely",
                "Because tax is charged on the difference"],
      answer: 0,
      why: "It is engineering tolerance for your own fallibility, not greed." },
    { q: "In Graham's metaphor, a sharply lower quote from Mr. Market is:",
      options: ["An offer, which you may accept, ignore, or take the other side of",
                "Evidence that your analysis was wrong",
                "A signal to cut the position",
                "The market's considered estimate of intrinsic value"],
      answer: 0,
      why: "The market is there to serve you, not to instruct you. Easy to agree with, very hard to act on." },
    { q: "A \"value trap\" is a business that is:",
      options: ["Cheap because it is genuinely deteriorating, so the low price is correct rather than mistaken",
                "Expensive relative to its growth rate",
                "Cheap because the market has not noticed it",
                "Illiquid enough that you cannot exit"],
      answer: 0,
      why: "A low multiple is a question, not an answer. The question is always why it is cheap and whether that reason is temporary." },
    { q: "At The Line, only wide disagreements between your read and the board were worth betting. What is the same idea called here?",
      options: ["Margin of safety", "Second-level thinking",
                "Reflexivity", "Adverse selection"],
      answer: 0,
      why: "A small disagreement is indistinguishable from your own measurement error. Same idea, same reason, different table." },
    { q: "Intrinsic value is best expressed as:",
      options: ["A range, held loosely enough to be honest about how little is knowable",
                "A single figure to two decimal places",
                "The current market capitalisation",
                "Book value plus a fixed premium"],
      answer: 0,
      why: "Graham never pretended otherwise, and everything else in the tier follows from taking that seriously." },
    { q: "A mediocre business bought very cheaply, versus a good business bought at a fair price:",
      options: ["The first pays once if the discount closes; the second keeps compounding without you having to be right again",
                "The first is always superior, since price is the only thing you control",
                "They are equivalent if the expected returns match",
                "The second is speculation rather than investing"],
      answer: 0,
      why: "The refinement Fisher, Lynch and later Buffett brought to the crude low-multiple screen." },
    { q: "Durability of earnings matters as much as the multiple because:",
      options: ["A discount only pays you once, whereas compounding earnings pay you repeatedly",
                "High multiples are always justified for quality",
                "Cheap stocks cannot be good businesses",
                "Earnings quality determines the tax treatment"],
      answer: 0,
      why: "Which is why the crude version of value investing walks straight into the value trap." },
  ],

  7: [
    { q: "Stripped of technique, an asset is worth:",
      options: ["The cash it will produce, discounted for the fact that later cash is worth less",
                "What the last buyer paid for a comparable asset",
                "The replacement cost of its assets",
                "Its earnings multiplied by the sector average multiple"],
      answer: 0,
      why: "Discounting is just tier two's interest arithmetic run backwards. The formula is trivial; the inputs are the argument." },
    { q: "Which input is simultaneously the most consequential and the least observable?",
      options: ["The discount rate", "This year's revenue",
                "The share count", "The tax rate"],
      answer: 0,
      why: "Two analysts with identical forecasts can produce valuations twice apart, purely from the rate. Ask for it first." },
    { q: "In a typical growth-company DCF, the terminal value is usually:",
      options: ["Most of the answer — often 60 to 80% of the total",
                "A small residual, under 10%",
                "Exactly half by construction",
                "Irrelevant if the forecast period is long enough"],
      answer: 0,
      why: "The decade you carefully modelled is the minority of the valuation. The majority rests on one perpetual-growth assumption." },
    { q: "Changing the terminal growth assumption by half a percentage point typically moves the valuation by:",
      options: ["Around 20%", "Around 1%", "Around 5%", "Around 100%"],
      answer: 0,
      why: "Which is why a valuation quoted to two decimal places should be read as a confession rather than a result." },
    { q: "The discount rate is conceptually:",
      options: ["A risk-free rate plus a premium for bearing this particular risk",
                "The company's cost of debt",
                "The expected growth rate of the business",
                "The central bank's policy rate"],
      answer: 0,
      why: "And the premium is estimated and contested, which means your discount rate is partly a market opinion, not a physical constant." },
    { q: "Damodaran's point about narrative and numbers is that:",
      options: ["A valuation needs both, and they have to be consistent with each other",
                "Narrative should be avoided as it introduces bias",
                "Numbers are decoration; the story does the work",
                "The narrative should be written after the model is finished"],
      answer: 0,
      why: "Most bad valuations are not arithmetic errors. They are stories the numbers quietly contradict." },
    { q: "£1 arriving in ten years, discounted at 8%, is worth roughly:",
      options: ["46p", "80p", "20p", "92p"],
      answer: 0,
      why: "1 ÷ 1.08^10 ≈ 0.46. Discounting is the same compounding from tier two, pointed the other way." },
    { q: "If your story is \"this becomes the dominant platform in its category\", the model must show:",
      options: ["A market large enough to contain that share, at margins that survive the competition the story implies",
                "Revenue growth above the sector average",
                "A terminal growth rate above GDP",
                "Positive cash flow within the forecast window"],
      answer: 0,
      why: "The discipline is finding which parts of the story the numbers are load-bearing for, and checking you believe those parts." },
  ],

  8: [
    { q: "Reflexivity, in Soros's sense, is:",
      options: ["Participants' beliefs altering the fundamentals those beliefs are about, which then alter the beliefs",
                "The tendency of prices to revert to their mean",
                "The reflex of selling after bad news",
                "The observation that markets are efficient in the long run"],
      answer: 0,
      why: "In physics the thermometer does not warm the room. In markets it does." },
    { q: "\"The market is wrong and will therefore correct\" can fail in a specific way. Which?",
      options: ["The market can be wrong in a way that makes itself right",
                "Corrections are always slower than expected",
                "The market is never wrong",
                "Corrections happen but are not tradeable after costs"],
      answer: 0,
      why: "A falling price can raise a firm's funding costs until the weakness the market feared becomes real." },
    { q: "Marks separates two questions. Which pair?",
      options: ["Forecasting what happens next, which is near-hopeless, and locating yourself in a cycle, which is feasible",
                "Buying cheaply and selling dearly",
                "Fundamental value and technical timing",
                "Systematic risk and idiosyncratic risk"],
      answer: 0,
      why: "\"We cannot predict, but we can prepare.\" Read as a sizing instruction, never a timing one." },
    { q: "The turkey problem shows that:",
      options: ["A long record of stability is weak evidence when the thing that could hurt you is not in the sample",
                "Rare events are impossible to survive",
                "Past returns are the best guide to future returns",
                "More data always produces better estimates"],
      answer: 0,
      why: "The turkey's confidence peaks, correctly by every measure available to it, the afternoon before Thanksgiving." },
    { q: "Second-level thinking asks:",
      options: ["Everyone already knows this is a good company, so where exactly is my return coming from?",
                "What is the second-order derivative of the price?",
                "What would a contrarian do here?",
                "How will this look on a longer timeframe?"],
      answer: 0,
      why: "You cannot earn an unusual return from a widely held view, because the widely held view is already the price." },
    { q: "An edge requires your view to be:",
      options: ["Both different from consensus and correct",
                "Different from consensus, which is sufficient",
                "Correct, whether or not it differs from consensus",
                "Held with more conviction than the consensus holds its own"],
      answer: 0,
      why: "Different and wrong is expensive. Same and right pays the average. You have been doing this since table nine." },
    { q: "A risk model calibrated entirely on a calm decade will:",
      options: ["Understate risk precisely on the days you are asking about",
                "Be conservative, since calm periods have little data",
                "Be accurate, since more recent data is more relevant",
                "Overstate risk because of survivorship bias"],
      answer: 0,
      why: "And nearly all of them are so calibrated, because calm periods are where most of the data lives." },
    { q: "Absence of evidence is not evidence of absence. Applied to markets, this means:",
      options: ["A risk that has not yet shown up in your sample has not been shown to be absent",
                "You should assume every risk is present until disproved",
                "Historical data cannot be used at all",
                "Only tail events matter for pricing"],
      answer: 0,
      why: "A thousand quiet days say nothing about the thousand-and-first." },
  ],

  9: [
    { q: "Volatility clustering means that what is predictable from one bar to the next?",
      options: ["The size of the move, but not its sign",
                "The sign of the move, but not its size",
                "Both the size and the sign",
                "Neither, which is why markets are efficient"],
      answer: 0,
      why: "Direction resists forecasting; magnitude does not. That single asymmetry is why professional risk management is possible at all.",
      chart: { kind: "clustering", seed: 61 } },
    { q: "In an equity GARCH model the β term typically sits near 0.9. What does that say?",
      options: ["Volatility is highly persistent — both calm and panic tend to last",
                "Volatility reacts violently to each new shock",
                "Volatility is essentially constant",
                "The model has been overfitted"],
      answer: 0,
      why: "α is how sharply volatility reacts to a shock; β is how long it stays elevated." },
    { q: "If α + β is close to but below 1, then after a shock volatility:",
      options: ["Decays back toward its long-run average rather than staying elevated forever",
                "Grows without limit",
                "Immediately returns to normal on the next bar",
                "Becomes unpredictable"],
      answer: 0,
      why: "Which is the formal statement of \"this too shall pass\"." },
    { q: "Under a normal distribution a five-sigma daily move should occur about once every seven thousand years. Actual markets produce them:",
      options: ["Several times a decade", "About once a century",
                "Roughly as often as the model predicts", "Only during recessions"],
      answer: 0,
      why: "The tails are fatter than the bell curve allows, and the shortfall sits exactly where the losses that matter live.",
      chart: { kind: "tails", seed: 23 } },
    { q: "When a risk system reports a one-in-a-thousand worst case, the honest translation is:",
      options: ["One in a thousand if the distributional assumption holds — and it is known to fail on exactly those days",
                "One in a thousand, as stated",
                "One in a hundred, after adjusting for fat tails",
                "The figure is meaningless and should be ignored"],
      answer: 0,
      why: "The assumption fails precisely on the days you are asking about, which is the whole problem with quoting it plainly." },
    { q: "Implied volatility is:",
      options: ["The market's forecast of the asset's future variability, expressed as a traded price",
                "The volatility realised over the past month",
                "A fixed input set by the exchange",
                "The volatility of the option's own price"],
      answer: 0,
      why: "Which closes a loop back to tier one: even volatility turns out to be a price, carrying information, set by disagreement." },
    { q: "Stochastic volatility models add the idea that:",
      options: ["Volatility has its own volatility, and reverts toward a level at some speed",
                "Volatility is constant but unobservable",
                "Returns are normally distributed after all",
                "Volatility can be perfectly hedged"],
      answer: 0,
      why: "Which is why pricing an option means forecasting not just where the asset goes but how agitated it will be on the way." },
    { q: "Why is professional risk management feasible when professional forecasting mostly is not?",
      options: ["Because magnitude is quite predictable while direction is close to a coin flip",
                "Because risk models are simpler than return models",
                "Because regulators mandate the methodology",
                "Because risk is measured after the fact"],
      answer: 0,
      why: "Returns ≈ unpredictable, but |returns| ≈ quite predictable. The entire discipline lives in that gap." },
  ],

  10: [
    { q: "A manager beats the index for a decade by holding small, cheap stocks. They have demonstrated:",
      options: ["Exposure, which anyone can buy for a few basis points",
                "Skill, since the benchmark was beaten",
                "Nothing measurable either way",
                "Skill, provided the outperformance was statistically significant"],
      answer: 0,
      why: "The right question stops being \"did they beat the market\" and becomes \"what were they exposed to, and could I have bought that directly?\"" },
    { q: "Alpha is defined as:",
      options: ["The part of a return your current factor model cannot explain",
                "Any return above the risk-free rate",
                "The return from active trading, before costs",
                "Outperformance against a peer group"],
      answer: 0,
      why: "Which means it is defined relative to your model — discover a new factor and yesterday's alpha becomes today's beta, retroactively." },
    { q: "Why must alpha be negative in aggregate after costs?",
      options: ["Every trade has a counterparty, so it is zero-sum before costs and costs are positive",
                "Because most managers are unskilled",
                "Because index funds have grown too large",
                "Because factor premia have been arbitraged away"],
      answer: 0,
      why: "None of which says skill does not exist. It says skill is scarce, shrinking, and very often mislabelled exposure." },
    { q: "The true cost of getting into and out of a position is:",
      options: ["Commission plus half the spread, plus slippage, plus market impact",
                "The commission alone",
                "The spread alone",
                "Zero at a commission-free broker"],
      answer: 0,
      why: "This is why a strategy can be profitable on paper and unprofitable in practice without anything about the idea being wrong." },
    { q: "Adverse selection explains why market makers:",
      options: ["Widen their spreads around news, because the flow arriving then is disproportionately informed",
                "Prefer to trade large orders",
                "Quote the same spread at all times",
                "Avoid liquid markets"],
      answer: 0,
      why: "Providing liquidity into informed flow is a losing trade, and everyone else pays the wider spread to cover it." },
    { q: "A backtest looked excellent and the live strategy lost money, with no error in the logic. The most likely cause is:",
      options: ["Transaction costs — spread, slippage and impact that the backtest assumed away",
                "The market regime changed on the first day of trading",
                "The data was fabricated",
                "The strategy was too diversified"],
      answer: 0,
      why: "Size moves the price against you, and the larger you are relative to the market the more it costs." },
    { q: "There is no single price for an asset because:",
      options: ["There is a bid somebody will buy at and an ask somebody will sell at, and the gap is a real cost",
                "Different exchanges report with a delay",
                "Prices are averages over the trading day",
                "Currency conversion introduces a spread"],
      answer: 0,
      why: "You pay it on the way in and again on the way out. It is the fee that never appears on a statement." },
    { q: "If you are consistently getting filled easily at the price you wanted, the question to ask is:",
      options: ["What does the person on the other side know that I do not?",
                "How can I increase my size?",
                "Why is my broker so efficient?",
                "Is the spread unusually narrow today?"],
      answer: 0,
      why: "Every fill has a counterparty who wanted the opposite. Sometimes they are hedging. Sometimes they know something." },
  ],
};

/** Deal a check: draw `n` questions from the tier's pool and shuffle each question's options. */
export function deal(tier, n) {
  const pool = (CHECKS[tier] || []).slice();
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(n, pool.length)).map((q) => {
    const idx = q.options.map((_, i) => i);
    for (let i = idx.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [idx[i], idx[j]] = [idx[j], idx[i]];
    }
    return {
      q: q.q,
      why: q.why,
      chart: q.chart,
      options: idx.map((i) => q.options[i]),
      answer: idx.indexOf(q.answer),
    };
  });
}

export const poolSize = (tier) => (CHECKS[tier] || []).length;
