// The nine tables. RTP and house-edge figures are the real casino numbers, because the
// whole premise is that the math the player learns is the math that exists.
export const TABLES = [
  {
    id: "reels",
    n: 1,
    name: "Sector Reels",
    form: "Slots — reels / RNG",
    skill: "Low",
    rtp: "94–97%",
    edge: "3–6%",
    teaches: "Diversification vs. concentration",
    blurb: "The reels are sectors, not cherries. Cover one and you own one stock. Cover all five and you own the index. Same expected return, wildly different ride.",
    status: "live",
  },
  {
    id: "sizing",
    n: 2,
    name: "The Sizing Table",
    form: "Blackjack — cards",
    skill: "High",
    rtp: "99%+",
    edge: "0.5–1%",
    teaches: "Position sizing and the Kelly criterion",
    blurb: "The only table where skill moves the number. Real six-deck blackjack at a 0.52% edge, with the count shown to you — so the question becomes how much to bet, not how to play.",
    status: "live",
  },
  {
    id: "wheel",
    n: 3,
    name: "The Wheel",
    form: "Roulette — wheel / table",
    skill: "Low",
    rtp: "94–97%",
    edge: "2.7–5.4%",
    teaches: "Idiosyncratic vs. systematic risk",
    blurb: "One number is one stock. A dozen is a sector. Red or black is stocks or cash. Every bet has the same −2.70% edge and up to six times the volatility — and the zero pocket is inflation.",
    status: "live",
  },
  {
    id: "twohands",
    n: 4,
    name: "Two Hands",
    form: "Baccarat — cards",
    skill: "Low",
    rtp: "98–99%",
    edge: "1–1.2%",
    teaches: "Fee drag over a lifetime",
    blurb: "Banker is the index fund. Player is the active fund. Tie pays 8:1 and has the worst expected value in the building — which is what every get-rich-quick pitch has in common.",
    status: "live",
  },
  {
    id: "pit",
    n: 5,
    name: "The Options Pit",
    form: "Craps — dice",
    skill: "Medium",
    rtp: "95–99%",
    edge: "1–5%",
    teaches: "Option payoffs and asymmetry",
    blurb: "Pass line is a call. Don't pass is a put. The free-odds bet is the only zero-edge wager in any casino, and it is how you learn what a fairly priced derivative looks like.",
    status: "live",
  },
  {
    id: "chase",
    n: 6,
    name: "Number Chase",
    form: "Bingo / Keno — lottery-style",
    skill: "None",
    rtp: "70–95%",
    edge: "5–30%",
    teaches: "Lottery brain",
    blurb: "The worst odds in the building, dressed as the best story. This is the penny stock, the meme ticker, the 0DTE call. You will lose here on purpose, and then understand why.",
    status: "live",
  },
  {
    id: "climb",
    n: 7,
    name: "The Climb",
    form: "Crash — multiplier / RNG",
    skill: "Low",
    rtp: "96–99%",
    edge: "1–4%",
    teaches: "Compounding and exit discipline",
    blurb: "A number climbs until it doesn't. Cash out whenever you like. Every exit point has the exact same expected value — and wildly different odds of surviving a hundred rounds.",
    status: "live",
  },
  {
    id: "book",
    n: 8,
    name: "The Book",
    form: "Live dealer",
    skill: "Medium",
    rtp: "96–99%",
    edge: "1–4%",
    teaches: "Spread, and who is across from you",
    blurb: "There is a person on the other side of the table taking the other side of your bet. That is a market maker, and the rake they take is the bid-ask spread.",
    status: "live",
  },
  {
    id: "line",
    n: 9,
    name: "The Line",
    form: "Sports / esports — odds-based",
    skill: "High",
    rtp: "90–98%",
    edge: "2–10%",
    teaches: "Odds as implied probability",
    blurb: "Every price is a probability wearing a disguise. Learn to read the line, back out what the market believes, and bet only when your number disagrees. That is fundamental analysis.",
    status: "live",
  },
];

export const byId = (id) => TABLES.find((t) => t.id === id);
